config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }, skip: [:registrations]

                  
  # admins pages
  resources 'admin'

  resources 'products', except: [:new]
  resources 'users'
  # resources 'sessions', only: [:new, :create, :destroy]
  

  delete '/logout', to: 'sessions#destroy'
  
  get 'static_pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  # root :to => redirect('/dashboard/dashboard_v1')
  root ('static_pages#home')
  # view routes
  get '/widgets' => 'widgets#index'

  get 'dashboard/dashboard_v1'
  get 'dashboard/dashboard_v2'
  get 'dashboard/dashboard_v3'
  get 'dashboard/dashboard_h'
  get 'elements/button'
  get 'elements/notification'
  get 'elements/spinner'
  get 'elements/animation'
  get 'elements/dropdown'
  get 'elements/nestable'
  get 'elements/sortable'
  get 'elements/card'
  get 'elements/portlet'
  get 'elements/grid'
  get 'elements/gridmasonry'
  get 'elements/typography'
  get 'elements/fonticons'
  get 'elements/weathericons'
  get 'elements/colors'
  get 'elements/buttons'
  get 'elements/notifications'
  get 'elements/carousel'
  get 'elements/tour'
  get 'elements/sweetalert'
  get 'forms/standard'
  get 'forms/extended'
  get 'forms/validation'
  get 'forms/wizard'
  get 'forms/upload'
  get 'forms/xeditable'
  get 'forms/imgcrop'
  get 'multilevel/level1'
  get 'multilevel/level3'
  get 'charts/flot'
  get 'charts/radial'
  get 'charts/chartjs'
  get 'charts/chartist'
  get 'charts/morris'
  get 'tables/standard'
  get 'tables/extended'
  get 'tables/datatable'
  get 'tables/bootgrid'
  get 'maps/google'
  get 'maps/vector'
  get 'extras/mailbox'
  get 'extras/timeline'
  get 'extras/calendar'
  get 'extras/invoice'
  get 'extras/search'
  get 'extras/todo'
  get 'extras/profile'
  get 'extras/contacts'
  get 'extras/contact_details'
  get 'extras/projects'
  get 'extras/project_details'
  get 'extras/team_viewer'
  get 'extras/social_board'
  get 'extras/vote_links'
  get 'extras/bug_tracker'
  get 'extras/faq'
  get 'extras/help_center'
  get 'extras/followers'
  get 'extras/settings'
  get 'extras/plans'
  get 'extras/file_manager'
  get 'blog/blog'
  get 'blog/blog_post'
  get 'blog/blog_articles'
  get 'blog/blog_article_view'
  get 'ecommerce/ecommerce_orders'
  get 'ecommerce/ecommerce_order_view'
  get 'ecommerce/ecommerce_products'
  get 'ecommerce/ecommerce_product_view'
  get 'ecommerce/ecommerce_checkout'
  get 'forum/forum_categories'
  get 'forum/forum_topics'
  get 'forum/forum_discussion'
  get 'pages/login'
  get 'pages/register'
  get 'pages/recover'
  get 'pages/lock'
  get 'pages/template'
  get 'pages/notfound'
  get 'pages/maintenance'
  get 'pages/error500'

  # api routes
  get '/api/datatable' => 'api#datatable'
  get '/api/i18n/:locale' => 'api#i18n'
  post '/api/xeditable' => 'api#xeditable'
  get '/api/xeditable-groups' => 'api#xeditablegroups'

  # the rest goes to root
  #  get '*path' => redirect('/')
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  enum roles: [ "super admin", "admin", "staff" ] 

  has_one_attached :avatar
  has_one_attached :cover_photo

  validates :name, length: { minimum: 2, maximum: 50 }, presence: true
  validates :bio, length: { minimum: 2, maximum: 500 }, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
    belongs_to :admin
    has_one_attached :image
    
    belongs_to :user
    has_one_attached :image
end

app/models/cover_photo.rb
class CoverPhoto < ApplicationRecord
    belongs_to :admin
    has_one_attached :image
    
    belongs_to :user
    has_one_attached :image
end

app/models/product.rb
class Product < ApplicationRecord
    validates :product_name, length: { minimum: 2, maximum: 50 }, presence: true
    validates :product_description, length: { minimum: 2, maximum: 240 }, presence: true
    validates :price, presence: true
    validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, length: { minimum: 2, maximum: 50 }, presence: true
    validates :email, presence: true
    validates :bio, length: { minimum: 2, maximum: 500 }, presence: true

    has_one_attached :avatar
    has_one_attached :cover_photo
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/extras_helper.rb
module ExtrasHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/multilevel_helper.rb
module MultilevelHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def login(user)
        session[:user_id] = user.id
    end

    def logged_in?
        !current_user.nil?
    end
    
    def only_loggedin_users
        redirect_to new_session_url, flash: { warning: "Please login first..."} unless logged_in?
    end

    def current_user?(user)
        user == current_user
    end
    
    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id:
            session[:user_id])
        end
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/admin/_form.html.erb
<%= form_for(@admin, url: admin_index_path(@admin), method: :post) do |f| %>
    <div class="form-group row">
        <%= f.label :name, class:"text-bold col-xl-2 col-md-3 col-4 col-form-label text-right"%>
        <div class="col-xl-10 col-md-9 col-8">
            <%= f.text_field :name, class:"form-control" %>                                
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :bio, class:"text-bold col-xl-2 col-md-3 col-4 col-form-label text-right"%>
        <div class="col-xl-10 col-md-9 col-8">
            <%= f.text_area :bio, rows: "4", class:"form-control" %>                                
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :email, class:"text-bold col-xl-2 col-md-3 col-4 col-form-label text-right"%>
        <div class="col-xl-10 col-md-9 col-8">
            <%= f.text_field :email, class:"form-control" %>                                
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :password, class:"text-bold col-xl-2 col-md-3 col-4 col-form-label text-right"%>
        <div class="col-xl-10 col-md-9 col-8">
            <%= f.password_field :password, class:"form-control" %>                                
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :password_confirmation, class:"text-bold col-xl-2 col-md-3 col-4 col-form-label text-right"%>
        <div class="col-xl-10 col-md-9 col-8">
            <%= f.password_field :password_confirmation, class:"form-control" %>                                
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :role, class: "text-bold col-xl-2 col-md-3 col-4 col-form-label text-right" %>
        <div class="col-xl-10 col-md-9 col-8">
        <%= f.select :role, options_for_select([
                                ["Super Admin"],
                                ["Admin"],
                                ["Staff"]
                            ], selected: f.object.role), {}, class: "custom-select"
                        %>
        </div>        
    </div>
    <div class="form-group row">
        <%= f.label :avatar, class: "text-bold col-xl-2 col-md-3 col-4 col-form-label text-right" %>
        <div class="col-xl-10 col-md-9 col-8">
            <%= f.file_field :avatar, class: "form-control filestyle", classbutton:"btn btn-secondary", lassinput:"form-control inline", icon:"&lt;span class='fa fa-upload mr'&gt;&lt;/span&gt;"%>
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :cover_photo, class: "text-bold col-xl-2 col-md-3 col-4 col-form-label text-right" %>
        <div class="col-xl-10 col-md-9 col-8">
            <%= f.file_field :cover_photo, class: "form-control filestyle", classbutton:"btn btn-secondary", lassinput:"form-control inline", icon:"&lt;span class='fa fa-upload mr'&gt;&lt;/span&gt;"%>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <%= f.submit class:"btn btn-block btn-info"%>
        </div>
    </div>
<% end %>

app/views/admin/index.html.erb
<div class="content-heading">
    <div>
    Admins
    <small>List of all Admin Accounts</small>
    </div>
    <% if admin_signed_in?  && current_admin.role == "Super Admin" %>
        <div class="ml-auto">
            <div class="btn-group">
                <button class="btn btn-link" data-toggle="dropdown">
                    <em class="fa fa-ellipsis-v fa-lg"></em>
                </button>
                <div class="dropdown-menu dropdown-menu-right-forced animated fadeInLeft" role="menu">
                    <a href="" class="dropdown-item" data-toggle="modal" data-target="#myModalLarge">
                        <em class='fa-fw fa fa-plus mr-2'></em> Add New Admin
                    </a>
                    
                </div>
            </div>
        </div>
    <% end %>
</div>
<div class="container-fluid">
   <!-- DATATABLE DEMO 1-->
   <div class="card">
      <div class="card-body">
         <table class="table table-striped my-4 w-100" id="datatable1">
            <thead>
               <tr>
                  <th data-priority="1">ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Bio</th>
                  <th>Role</th>
                  <th>Actions</th>
               </tr>
            </thead>
            <tbody>
               <% @admins.each do |admin| %>
                  <tr>
                     <td><%= admin.id %></td>
                     <td>
                        <% if admin.avatar.attached? %>
                           <%= image_tag admin.avatar, class:"img-thumbnail rounded-circle", width: 60, height: 60%>
                        <% else %>
                           <img src="<%= image_path('angle/user/03.jpg') %>" alt="Avatar" width="60" height="60" class="img-thumbnail rounded-circle" />
                        <% end %> &nbsp;
                        <%= admin.name %>
                     </td>
                     <td><%= admin.email %></td>
                     <td><%= admin.bio %></td>
                     <td><%= admin.role %></td>
                     <td> 
                           <%= link_to "View", admin_path(admin),class:"btn btn-primary"%>
                           <% if current_admin.role == "Super Admin"  || current_admin.role == "Admin" && admin.role != "Super Admin" %>
                              <%= link_to "Edit", edit_admin_path(admin), class: "btn btn-info" %>
                              <%= link_to "Delete", admin_path(admin), class: "btn btn-danger", data: { confirm_swal: '', remote: true, method: 'DELETE' }  %>
                           <% end %>
                     </td>
                  </tr>
               <% end %>
            </tbody>
         </table>
      </div>
   </div>
</div>
<% content_for :body_area do %>
    <!-- Modal Large-->
    <div class="modal fade" id="myModalLarge" tabindex="-1" role="dialog" aria-labelledby="myModalLabelLarge" aria-hidden="true">
       <div class="modal-dialog modal-lg">
          <div class="modal-content">
             <div class="modal-header">
                <h4 class="modal-title" id="myModalLabelLarge">Modal title</h4>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
                </button>
             </div>
             <div class="modal-body">
                <%= render 'form' %>
             </div>
          </div>
       </div>
    </div>
<% end %>

app/views/admin/show.html.erb
<div class="unwrap">
    <% if @cover_photo.attached? %>
        <div style="background-image: url(<%= url_for(@cover_photo) %>)" class="bg-cover">
    <% else %>
        <div style="background-image: url(<%= asset_path 'angle/profile-bg.jpg' %>)" class="bg-cover">
    <% end %>

        <div class="p-4 text-center text-white">
            <% if @avatar.attached? %>
                <%= image_tag @avatar, class:"img-thumbnail rounded-circle thumb128"%>
            <% else %>
                <img class="img-thumbnail rounded-circle thumb128" src="<%= image_path('angle/user/09.jpg') %>" alt="Image" />
            <% end %>
            <h3 class="m-0"><%= @admin.name %></h3>
            <p><%= @admin.email%></p>
        </div>
    </div>
    <div class="p-3">
        <div class="row">
            <div class="col-lg-8">
                <div class="card card-default mb-3">
                    <div class="card-header">Admin Information</div>
                    <div class="card-body">
                        <h5 class="card-title">Bio</h5>
                        <p class="card-text"><%= @admin.bio %></p>
                        <%= link_to 'Action', '#link-to-some-page', data: { confirm_swal: 'hello world' }%>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="card card-default">
                    <div class="card-body">
                        <% if @admin == current_admin %>
                            <div class="row">
                                <div class="col-12 d-flex justify-content-center">
                                    <%= link_to "Edit Admin", edit_admin_path(@admin), class: "btn btn-pill-left btn-info" %>
                                    <%= link_to "Delete Admin", admin_path(@admin), class: "btn btn-pill-right btn-danger", data: { confirm_swal: '', remote: true, method: 'DELETE' } %>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admins/index.html.erb
<div class="content-heading">
    <div>
    Admins
    <small>List of all Admin Accounts</small>
    </div>
    <% if admin_signed_in? %>
        <div class="ml-auto">
            <div class="btn-group">
                <button class="btn btn-link" data-toggle="dropdown">
                    <em class="fa fa-ellipsis-v fa-lg"></em>
                </button>
                <div class="dropdown-menu dropdown-menu-right-forced animated fadeInLeft" role="menu">
                    <a href="" class="dropdown-item" data-toggle="modal" data-target="#myModalLarge">
                        <em class='fa-fw fa fa-plus mr-2'></em> Add New Admin
                    </a>
                    
                </div>
            </div>
        </div>
    <% end %>
</div>
<div class="container-fluid">
   <!-- DATATABLE DEMO 1-->
   <div class="card">
      <div class="card-body">
         <table class="table table-striped my-4 w-100" id="datatable1">
            <thead>
               <tr>
                  <th data-priority="1">ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th>Actions</th>
               </tr>
            </thead>
            <tbody>
                <% @admins.each do |admin| %>
                <tr>
                    <td><%= admin.id %></td>
                    <td><%= admin.name %></td>
                    <td><%= admin.email %></td>
                    <td><%= admin.role %></td>
                    <td>
                        <%= link_to "Edit", edit_admin_registration_path(admin), class: "btn btn-info" %>
                        <button class="btn btn-danger">
                            Delete
                        </button>
                    </td>
                </tr>
               <% end %>
            </tbody>
         </table>
      </div>
   </div>
</div>
<% content_for :body_area do %>
    <!-- Modal Large-->
    <div class="modal fade" id="myModalLarge" tabindex="-1" role="dialog" aria-labelledby="myModalLabelLarge" aria-hidden="true">
       <div class="modal-dialog modal-lg">
          <div class="modal-content">
             <div class="modal-header">
                <h4 class="modal-title" id="myModalLabelLarge">Modal title</h4>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
                </button>
             </div>
             <div class="modal-body">
                <%= render 'form' %>
             </div>
             <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
                <button class="btn btn-primary" type="button">Save changes</button>
             </div>
          </div>
       </div>
    </div>
<% end %>

app/views/layouts/partials/_footer.html.erb
<span>&copy; 2020 - Angle</span>

app/views/layouts/partials/_messages.html.erb
<% if flash.any? %>
    <% flash.each do |type, msg| %>
        <div class="alert <% if type == 'notice' %> alert-success <% else %> alert-warning <% end %>  alert-dismissible fade show" role="alert">
            <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <%= msg %>
        </div>
    <% end %>
<% end %>

app/views/layouts/partials/_sidebar.html.erb
<!-- START Sidebar (left)-->
<div class="aside-inner">
   <nav class="sidebar" data-sidebar-anyclick-close="">
      <!-- START sidebar nav-->
      <ul class="sidebar-nav">
         <% if admin_signed_in? %>
         <!-- START user info-->
         <li class="has-user-block">
            <div id="user-block" class="collapse show">
               <div class="item user-block">
                  <!-- User picture-->
                  <div class="user-block-picture">
                     <div class="user-block-status">
                        <% if current_admin.avatar.attached? %>
                           <%= image_tag current_admin.avatar, class:"img-thumbnail rounded-circle", width:100, height:100 %>
                        <% else %>
                           <img src="<%= image_path('angle/user/02.jpg') %>" alt="Avatar" width="60" height="60" class="img-thumbnail rounded-circle" />
                        <% end %>
                        <div class="circle circle-success circle-lg"></div>
                     </div>
                  </div>
                  <!-- Name and Job-->
                  <div class="user-block-info">
                     <span class="user-block-name">Hello, <%= link_to current_admin.name, admin_path(current_admin) %></span>
                     <span>
                        <%= button_to destroy_admin_session_path, method: :delete, class: "btn btn-link text-primary" do %>
                           <em class='icon-logout'></em>&nbsp;&nbsp;Logout
                        <% end %>
                     </span>
                  </div>
               </div>
            </div>
         </li>
         <!-- END user info-->
         <!-- Iterates over all sidebar items-->
         <li class="nav-heading">
            <span data-localize="sidebar.heading.HEADER">Main Navigation</span>
         </li>
         <li class="<%= 'active' if controller?('home')%>">
            <a href="#home" title="Dashboard" data-toggle="collapse">
               <div class="badge badge-info float-right">3</div>
               <em class="icon-speedometer"></em>
               <span data-localize="sidebar.nav.DASHBOARD">Dashboard</span>
            </a>
            <ul id="home" class="sidebar-nav sidebar-subnav collapse <%= 'show' if controller?('home') %>">
               <li class="sidebar-subnav-header">Dashboard</li>
               <li class="<%= 'active' if controller?('home') %>">
                  <a href="/" title="Home">
                     <em class="icon-home"></em>
                     <span>Home</span>
                  </a>
               </li>
               <li class="<%= 'active' if controller?('users') %>">
                  <%= link_to users_path, title:"Users" do %>
                        <div class="badge badge-info float-right"><%= User.all.count %></div>
                        <em class='fas fa-users'></em>
                        <span>Users</span>
                  <% end %>
               </li>
               <li class="<%= 'active' if controller?('products') %>">
                  <%= link_to products_path, title:"Products"  do %>
                        <div class="badge badge-info float-right"><%= Product.all.count %></div>
                        <em class='fas fa-boxes'></em>
                        <span>Products</span>
                  <% end %>
               </li>
               <% if admin_signed_in? %>
                  <li class="<%= 'active' if controller?('admin') %>">
                     <a href="#Admin" title="Admins" data-toggle="collapse">
                     <div class="badge badge-info float-right"><%= Admin.all.count %></div>
                        <em class="fa fa-crown"></em>
                        <span>Admins</span>
                     </a>
                     <ul id="Admin" class="sidebar-nav sidebar-subnav collapse">
                        <li class="sidebar-subnav-header">Admins</li>
                        <li>
                           <%= link_to raw("<span>Admin List</span>"), admin_index_path, title: "Admin List" %>
                        </li>
                        <li>
                           <%= link_to raw("<span>Admin Profile</span>"), admin_path(current_admin), title: "Admins Profile" %>
                        </li>
                        <li>
                           <a>
                              <%= button_to "Logout", destroy_admin_session_path, class: "btn btn-link", title: "Logout", method: :delete %>
                           </a>
                        </li>
                     </ul>
                  </li>
               <% end %>
            </ul>
         </li>
         <% else %>
            <li class="nav-heading">
               <span>Admin Navigation</span>
            </li>
            <li class="<%= 'active' if controller?('devise/sessions') %>">
               <a href="/admins/sign_in" title="Admin Login">
                  <em class="fa fa-sign-in-alt"></em>
                  <span>Admin Login</span>
               </a>
            </li>
         <% end %>
         <li class="nav-heading">
            <span>Demo Navigation</span>
         </li>

         <li class="<%= 'active' if controller?('multilevel') %>">
            <a href="#multilevel" title="Multilevel" data-toggle="collapse">
               <em class="far fa-folder-open"></em>
               <span>Demo Pages</span>
            </a>
            <ul id="multilevel" class="sidebar-nav sidebar-subnav collapse <%= 'show' if controller?('multilevel') %>">
               <li class="sidebar-subnav-header">Demo Pages</li>
               <%= render'layouts/partials/demo_links' %>
            </ul>
         </li>
      </ul>
      <!-- END sidebar nav-->
   </nav>
</div>
<!-- END Sidebar (left)-->

app/views/layouts/partials/_topnavbar.html.erb
<!-- START Top Navbar-->
<nav class="navbar topnavbar">
    <!-- START navbar header-->
    <div class="navbar-header">
        <a class="navbar-brand" href="/">
            <div class="brand-logo">
                <img class="img-fluid" src="<%= image_path('angle/logo.png') %>" alt="App Logo">
            </div>
            <div class="brand-logo-collapsed">
                <img class="img-fluid" src="<%= image_path('angle/logo-single.png') %>" alt="App Logo">
            </div>
        </a>
    </div>
    <!-- END navbar header-->
    <!-- START Left navbar-->
    <ul class="navbar-nav mr-auto flex-row">
        <li class="nav-item">
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a class="nav-link d-none d-md-block d-lg-block d-xl-block" href="#" data-trigger-resize="" data-toggle-state="aside-collapsed">
            <em class="fas fa-bars"></em>
            </a>
            <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
            <a class="nav-link sidebar-toggle d-md-none" href="#" data-toggle-state="aside-toggled" data-no-persist="true">
            <em class="fas fa-bars"></em>
            </a>
        </li>
        <!-- START User avatar toggle-->
        <% if admin_signed_in? %>
        <li class="nav-item d-none d-md-block">
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a class="nav-link" id="user-block-toggle" href="#user-block" data-toggle="collapse">
            <em class="icon-user"></em>
            </a>
        </li>
        <!-- END User avatar toggle-->
        <% else %>
        <!-- START login screen-->
        <li class="nav-item d-none d-md-block">
            <%= link_to raw("<em class='fa fa-sign-in-alt'></em>"), new_admin_session_path, title:"Login", class:"nav-link" %>
        </li>
        <% end %>
        <!-- END login screen-->
    </ul>
    <!-- END Left navbar-->
    <!-- START Right Navbar-->
    <ul class="navbar-nav flex-row">
        <% if admin_signed_in? %>
        <!-- Search icon-->
        <li class="nav-item">
            <a class="nav-link" href="#" data-search-open="">
            <em class="icon-magnifier"></em>
            </a>
        </li>
        <% end %>
        <!-- Fullscreen (only desktops)-->
        <li class="nav-item d-none d-md-block">
            <a class="nav-link" href="#" data-toggle-fullscreen="">
            <em class="fa fa-expand"></em>
            </a>
        </li>
        <% if admin_signed_in? %>
        <!-- START Alert menu-->
        <li class="nav-item dropdown dropdown-list">
            <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href="#" data-toggle="dropdown">
            <em class="icon-bell"></em>
            <span class="badge badge-danger">11</span>
            </a>
            <!-- START Dropdown menu-->
            <div class="dropdown-menu dropdown-menu-right animated flipInX">
                <div class="dropdown-item">
                    <!-- START list group-->
                    <div class="list-group">
                        <!-- list item-->
                        <div class="list-group-item list-group-item-action">
                            <div class="media">
                                <div class="align-self-start mr-2">
                                    <em class="fab fa-twitter fa-2x text-info"></em>
                                </div>
                                <div class="media-body">
                                    <p class="m-0">New followers</p>
                                    <p class="m-0 text-muted text-sm">1 new follower</p>
                                </div>
                            </div>
                        </div>
                        <!-- list item-->
                        <div class="list-group-item list-group-item-action">
                            <div class="media">
                                <div class="align-self-start mr-2">
                                    <em class="fa fa-envelope fa-2x text-warning"></em>
                                </div>
                                <div class="media-body">
                                    <p class="m-0">New e-mails</p>
                                    <p class="m-0 text-muted text-sm">You have 10 new emails</p>
                                </div>
                            </div>
                        </div>
                        <!-- list item-->
                        <div class="list-group-item list-group-item-action">
                            <div class="media">
                                <div class="align-self-start mr-2">
                                    <em class="fa fa-tasks fa-2x text-success"></em>
                                </div>
                                <div class="media-body">
                                    <p class="m-0">Pending Tasks</p>
                                    <p class="m-0 text-muted text-sm">11 pending task</p>
                                </div>
                            </div>
                        </div>
                        <!-- last list item-->
                        <div class="list-group-item list-group-item-action">
                            <span class="d-flex align-items-center">
                            <span class="text-sm">More notifications</span>
                            <span class="badge badge-danger ml-auto">14</span>
                            </span>
                        </div>
                    </div>
                    <!-- END list group-->
                </div>
            </div>
            <!-- END Dropdown menu-->
        </li>
        <% end %>
        <!-- END Alert menu-->
        <!-- START Offsidebar button-->
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
            <em class="icon-notebook"></em>
            </a>
        </li>
        <!-- END Offsidebar menu-->
    </ul>
    <!-- END Right Navbar-->
    <!-- START Search form-->
    <form class="navbar-form" role="search" action="search.html">
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Type and hit enter ...">
            <div class="fa fa-times navbar-form-close" data-search-dismiss=""></div>
        </div>
        <button class="d-none" type="submit">Submit</button>
    </form>
    <!-- END Search form-->
</nav>
<!-- END Top Navbar-->